"""Guard: the runtime-shipped manifest must exist and match the ingestion source.

The regulation manifest drives version filtering (which superseded PSTOs to hide)
and program detection. It ships as ``backend/data/manifest.json``; the source of
truth is ``documents/manifest.json`` (regenerated by the scraper). If they drift,
the deployed bot filters against a stale version list — or, if missing entirely,
serves outdated regulations. See app/paths.py and app/search/version_registry.py.
"""
import json
from pathlib import Path

import pytest

_BACKEND_ROOT = Path(__file__).resolve().parent.parent
_SHIPPED = _BACKEND_ROOT / "data" / "manifest.json"
_SOURCE = _BACKEND_ROOT.parent / "documents" / "manifest.json"


def test_shipped_manifest_present():
    assert _SHIPPED.exists(), (
        "backend/data/manifest.json is missing — it must ship with the backend so "
        "version filtering + program detection work in production."
    )


@pytest.mark.skipif(
    not _SOURCE.exists(),
    reason="documents/manifest.json (ingestion source) not present in this checkout",
)
def test_shipped_manifest_in_sync_with_source():
    shipped = json.loads(_SHIPPED.read_text())
    source = json.loads(_SOURCE.read_text())
    assert shipped == source, (
        "backend/data/manifest.json is stale vs documents/manifest.json. "
        "Re-copy after re-ingesting: cp documents/manifest.json backend/data/manifest.json"
    )
